// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("Counter");

function string(prim) {
  return prim;
}

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (param) {
      var send = param[/* send */4];
      var msg = "Current Count:  " + Pervasives.string_of_int(param[/* state */2][/* count */0]);
      return React.createElement("div", undefined, React.createElement("h2", undefined, msg), React.createElement("button", {
                      onClick: (function () {
                          return Curry._1(send, /* Increment */0);
                        })
                    }, "+"), React.createElement("button", {
                      onClick: (function () {
                          return Curry._1(send, /* Decrement */1);
                        })
                    }, "-"));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* count */0];
    });
  newrecord[/* reducer */12] = (function (action, state) {
      if (action !== 0) {
        return /* Update */Block.__(0, [/* record */[/* count */state[/* count */0] - 1 | 0]]);
      } else {
        return /* Update */Block.__(0, [/* record */[/* count */state[/* count */0] + 1 | 0]]);
      }
    });
  return newrecord;
}

exports.component = component;
exports.string = string;
exports.make = make;
/* component Not a pure module */
