// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("HelloWorld");

function str(prim) {
  return prim;
}

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("h2", undefined, "Hello there world!");
    });
  return newrecord;
}

exports.component = component;
exports.str = str;
exports.make = make;
/* component Not a pure module */
